[graph]
all-features = true

[advisories]
ignore = [
    # ed25519-dalek 1.0.1
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2022-0093
    # Versions of `ed25519-dalek` prior to v2.0 model private and public keys as
    # separate types which can be assembled into a `Keypair`, and also provide APIs
    # for serializing and deserializing 64-byte private/public keypairs.
    "RUSTSEC-2022-0093",

    # curve25519-dalek 3.2.1
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0344
    # Timing variability of any kind is problematic when working with  potentially secret values such as
    # elliptic curve scalars, and such issues can potentially leak private keys and other secrets. Such a
    # problem was recently discovered in `curve25519-dalek`.
    "RUSTSEC-2024-0344",

    # proc-macro-error 1.0.4
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0370
    "RUSTSEC-2024-0370",

    # paste 1.0.15
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0436
    "RUSTSEC-2024-0436",

    # idna 0.5.0
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0421
    "RUSTSEC-2024-0421",

    # derivative 2.2.0
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0388
    "RUSTSEC-2024-0388",

    # protobuf 2.28.0
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0437
    "RUSTSEC-2024-0437",
]
